### ISSUE TITLE
Suggestion, not really an issue

### ISSUE THREAD

**Issue by gerkovink** [cjvanlissa/gitbook-demo#1]
Hi Caspar,

Mooi initiatief. Ik zie dat je de Creative Commons licenses promoot. Ik ben zelf voor dit soort code exercities fan van de GNU GPL versie 3. Misschien een idee om toe te voegen. Hieronder mijn standaard motivatie voor deze licentie.

*I publish all my work under a GNU GPL v3 copyleft licence. You are free to use all materials, as long as you leave the responsibilities and freedom of the materials intact. For example, with respect to the course materials and software that I developed, if you distribute copies or parts thereof, whether gratis or for a fee, you must pass on to the recipients the same freedoms that you received. You must make sure that they, too, receive or can get the source code. And you must show them these terms so they know their rights.*

Groet,

Gerko

**Comment by cjvanlissa** [comment]
Thanks Gerko! Ik zal GNU GPL 3 toevoegen. Ik ben nu samen met Barbara Vreede aan het uitzoeken welke licenties het best zijn voor deze dingen, vooralsnog heb ik zelf vooral ervaring met CC.

**Comment by cjvanlissa** [comment]
Done
